# Site settings
title: dndmeir
email: rebbdohr@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site is powered by jekyll and GitHub Pages
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dondemeier.github.io“ # the base hostname & protocol for your site
twitter_username: dondemeier
github_username:  dondemeier

# Build settings
markdown: kramdown
